name: Deploy Authenticator Microservice

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build com Maven
        run: mvn clean package -DskipTests

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerceproduct:latest .

      - name: Push da imagem Docker
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ecommerceproduct:latest

      - name: Deploy na EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Criando rede ecommerce-net (se não existir)..."
            docker network inspect ecommerce-net >/dev/null 2>&1 || docker network create ecommerce-net

            echo "Parando e removendo container antigo..."
            docker stop ecommerceproduct || true
            docker rm ecommerceproduct || true

            echo "Puxando nova imagem..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/ecommerceproduct:latest

            echo "Subindo novo container..."
            docker run -d --name ecommerceproduct -p 8082:8080 --network ecommerce-net ${{ secrets.DOCKER_USERNAME }}/ecommerceproduct:latest
